<?php

/**
 * @file
 * Implements hook_library();
 */
function jqplot_charts_library() {

  $libraries['jqplot'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts') . '/jquery.jqplot.js' => array('group' => JS_LIBRARY, 'weight' => 0),
      libraries_get_path('jqplot_charts') . '/plugins/jqplot.pointLabels.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'css' => array(
      libraries_get_path('jqplot_charts') . '/jquery.jqplot.css' => array('group' => CSS_DEFAULT),
    ),
  );

  $libraries['jqplot.json2'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.json2.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.barRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.barRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.BezierCurveRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.BezierCurveRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.blockRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.blockRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.bubbleRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.bubbleRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.canvasAxisLabelRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.canvasAxisLabelRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.canvasAxisTickRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.canvasAxisTickRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  // Canvas Overlay plugin
  $libraries['jqplot.canvasOverlay'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.canvasOverlay.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  // Canvas text renderer
  $libraries['jqplot.canvasTextRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.canvasTextRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  // Catagory text renderer
  $libraries['jqplot.categoryAxisRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.categoryAxisRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.ciParser'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.ciParser.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.cursor'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts') . '/plugins/jqplot.cursor.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.dateAxisRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts') . '/plugins/jqplot.dateAxisRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.donutRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.donutRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.dragable'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.dragable.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.enhancedLegendRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.enhancedLegendRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.funnelRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.funnelRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.highlighter'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.highlighter.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.logAxisRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.logAxisRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.mekkoAxisRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.mekkoAxisRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.mekkoRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.mekkoRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.meterGaugeRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.meterGaugeRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.mobile'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.mobile.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.ohlcRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.ohlcRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.pieRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.pieRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.pointLabels'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.pointLabels.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.pyramidAxisRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.pyramidAxisRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.pyramidGridRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.pyramidGridRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.pyramidRenderer'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.pyramidRenderer.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  $libraries['jqplot.trendline'] = array(
    'name' => 'jQPlot charting library',
    'vendor url' => 'www.jqplot.com/',
    'download url' => 'www.jqplot.com/',
    'version' => '1.0.8',
    'js' => array(
      libraries_get_path('jqplot_charts'). '/plugins/jqplot.trendline.js' => array('group' => JS_LIBRARY, 'weight' => 0),
    ),
    'dependencies' => array(
      array('jqplot_charts', 'jqplot'),
    ),
  );

  return $libraries;
}
